### ISSUE TITLE
Rebase against upstream to have more features and potential fixes

### ISSUE THREAD

**Issue by TimDaub** [leapdao/MultiSigWallet#7]
## Scope
E.g. wallet.leapdao.org doesn't have Address Book feature yet. So we'd like to take all progress from upstream

## Gains

- Address book makes sending DAI much easier as you don't have to always confirm addresses when paying contributors

## Roles
Gardener @TimDaub 10%
Worker 75%
Reviewer 15%

**Comment by troggy** [comment]
Resolved in master branch  — force pushed after rebase on upstream + 5faa66c83465c4328ba17427e3a94fb1e6992411, d6a17055c41f452742f5469fe4b5c2f091e4687e, be9dd55b2912120ed12ad020dc35a41627ea6dac

Some extras:
- add address book to "Withdraw Token" d354655044717e972444373bde7d51cec89ff6b9 + upstream PR https://github.com/gnosis/MultiSigWallet/pull/288
- Leapified favicon and logo. 610c219ff58163d8330b651934cfbbab2d10035f
- a little less ugly icon-only buttons 0c5fe99bcee6b98de85eda5eec932a857f0b1707

Let me know if anything is broken

**Comment by troggy** [comment]
done
