### ISSUE TITLE
better interface for bounty-payout

### ISSUE THREAD

**Issue by johba37** [leapdao/MultiSigWallet#8]
# Bounty

the current way to talk the [bounty payout contract](https://github.com/leapdao/leap-contracts/blob/master/contracts/misc/BountyPayout.sol) is very unintuitive.

<img width="891" alt="Screen Shot 2019-10-23 at 4 52 27 PM" src="https://user-images.githubusercontent.com/659301/67405942-b4a35700-f5b5-11e9-801a-00dbbbe75013.png">

gardeners often forget to add 18 zeros to the end of amounts, or don't know how to convert string to hex for the issueID (last field).

## Scope

- add additional button next to "Add DAI tx"
- create an input field that can work for `payout()`, `payoutNoWorker()`, and `payoutNoReviewer()` functions
- automatically add zeros and convert string to hex

## Deliverables

- code
- deployed at [wallet.leapdao.org](https://wallet.leapdao.org)

## Gain for the project

- better integration with colony network contracts

### Publicly visible delivery

- blog post about new UI + colony integration

## Roles
bounty gardener: @troggy  / 50 DAI flat
bounty worker: @eswarasai / 85%, 425 DAI
bounty reviewer: name / 15%, 75 DAI

**Comment by troggy** [comment]
@johannbarbie free for grabs as I see? Can I take it? Which multisig pays for it?

**Comment by eswarasai** [comment]
@troggy - I've already tried to take a stab at it but I'm stuck to get the `BountyPayout` contract deployed to Rinkeby and see how it all connects. Let me know if you can help me out here or you'd like to wrap it up. Thanks 🙂

**Comment by troggy** [comment]
> I'm stuck to get the BountyPayout contract deployed to Rinkeby

what have you tried already?

**Comment by eswarasai** [comment]
I haven't tried deploying the `BountyPayout` contract to Rinkeby since @johannbarbie told that he'd take care of it. I've setup the repo locally already. What I need are below:
1) `BountyPayout` contract deployed to Rinkeby
2) How/Where to implement the above UI and talk to the deployed contract within this repo

**Comment by troggy** [comment]
@eswarasai how is going? 👋 It is been a while, I'd love to see draft Pull Request with work in progress. Thanks

**Comment by eswarasai** [comment]
@troggy - Sorry about the delay here. I'll be opening a draft WIP PR today EOD. Thanks!
